LogLevel: 0 # debug

Metrics:
  HealthCheckRoute: "/healthcheck"
  MetricsRoute: "/metrics"
  Socket: "0.0.0.0:8888"

QueueConsumer:
  Socket: "idempotencer:8887"

QueueProducer:
  Socket: "idempotencer:8886"

QueueBroker:
  InSocket:  "0.0.0.0:8886"
  OutSocket: "0.0.0.0:8887"


