version: "3.7"
services:

  idempotencer-dev:
    container_name: idempotencer-dev
    hostname: idempotencer-dev
    build:
      context: ./../
      image: c1rno/idempotencer
      dockerfile: deployments/Dockerfile
    networks:
      - idempotencer

networks:
  idempotencer:
